# http://about.travis-ci.org/docs/user/languages/python/

language: python
python:
  - "2.7"

install: 
  - pip install -r requirements.txt --use-mirrors

before_script:
  - pip install -r test_requirements.txt --use-mirrors

script: 
  - py.test --doctest-modules --pep8 mwtemplates --cov mwtemplates --cov-report term-missing

after_success:
  - coveralls
