# http://about.travis-ci.org/docs/user/languages/python/

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install: 
  - python setup.py install

before_script:
  - pip install -r test_requirements.txt

script: 
  - py.test --pep8 mwtemplates -v --cov mwtemplates --doctest-modules -x tests

after_success:
  - coveralls
